openapi: 3.1.0
info:
  version: 1.0.0
  title: api.weikuwu.me
  x-logo:
    url: https://raw.githubusercontent.com/AiverAiva/weikuwu.me/main/assets/img/logoBig_pwOl.png
servers:
  - url: https://api.weikuwu.me/
tags:
  - name: Basic
    description: Basic checks to the api.
  - name: osu
    description: osu! related endpoints.
paths:
  /hello:
    post:
      tags:
        - Basic
      summary: hello world test
      description: This test exist for checking the api is still alive.
      operationId: hello
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
              examples:
                response:
                  value: Hello world!
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            read:users: read users info
            write:users: modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
